// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_BANTpnl;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_STEPpnl;
lv_obj_t * ui_stepLBL;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_batLBL;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_Label5;
lv_obj_t * ui_disLBL;
lv_obj_t * ui_tresLBL2;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label3;
lv_obj_t * ui_StepdisLBL;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Label11;
lv_obj_t * ui_secLBL;
lv_obj_t * ui_Label13;
lv_obj_t * ui_speedLBL;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Label14;
lv_obj_t * ui_caloriesLBL;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Label16;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_Label17;
lv_obj_t * ui_Label18;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Label19;
lv_obj_t * ui_BANTpnl1;
lv_obj_t * ui_Spinner2;
lv_obj_t * ui_sleepBar;
lv_obj_t * ui_sndPNL;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_crgPNL;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_weightLBL2;
lv_obj_t * ui_Label29;
lv_obj_t * ui_Panel8;


// SCREEN: ui_setScreen
void ui_setScreen_screen_init(void);
lv_obj_t * ui_setScreen;
lv_obj_t * ui_tresLBL;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label6;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label7;
void ui_event_Button5(lv_event_t * e);
lv_obj_t * ui_Button5;
lv_obj_t * ui_Label20;
void ui_event_Button6(lv_event_t * e);
lv_obj_t * ui_Button6;
lv_obj_t * ui_Label4;
void ui_event_Button7(lv_event_t * e);
lv_obj_t * ui_Button7;
lv_obj_t * ui_Label9;
lv_obj_t * ui_StepdisLBL1;
void ui_event_brightSLI(lv_event_t * e);
lv_obj_t * ui_brightSLI;
void ui_event_weightDOWN(lv_event_t * e);
lv_obj_t * ui_weightDOWN;
lv_obj_t * ui_Label21;
lv_obj_t * ui_Label22;
lv_obj_t * ui_Label23;
void ui_event_weightUP(lv_event_t * e);
lv_obj_t * ui_weightUP;
lv_obj_t * ui_Label24;
lv_obj_t * ui_Label25;
lv_obj_t * ui_soundLBL;
lv_obj_t * ui_brightnessLBL;
void ui_event_soundOnBTN(lv_event_t * e);
lv_obj_t * ui_soundOnBTN;
lv_obj_t * ui_Label27;
void ui_event_soundOffBTN(lv_event_t * e);
lv_obj_t * ui_soundOffBTN;
lv_obj_t * ui_Label28;
lv_obj_t * ui_weightLBL;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Spinner1;
lv_obj_t * ui_Label26;
lv_obj_t * ui_Image3;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_1745987039[1] = {&ui_img_2038933285};
const lv_img_dsc_t * ui_imgset_1656268395[2] = {&ui_img_1537598557, &ui_img_440250019};
const lv_img_dsc_t * ui_imgset_284505786[1] = {&ui_img_597475696};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        setTreshold(e);
    }
}
void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_setScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_setScreen_screen_init);
    }
}
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        setTreshold(e);
    }
}
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        setTreshold(e);
    }
}
void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        setSDist(e);
    }
}
void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        setSDist(e);
    }
}
void ui_event_brightSLI(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        briChanged(e);
        _ui_slider_set_text_value(ui_brightnessLBL, target, "Brightness: ", "");
    }
}
void ui_event_weightDOWN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        setWeight(e);
    }
}
void ui_event_weightUP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        setWeight(e);
    }
}
void ui_event_soundOnBTN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        soundOnOFF(e);
    }
}
void ui_event_soundOffBTN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        soundOnOFF(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_setScreen_screen_init();
    ui_Screen2_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
