// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Screen1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Screen1, &ui_img_logo_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_Screen1, 40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 15);
    lv_obj_set_y(ui_Label1, 40);
    lv_label_set_text(ui_Label1, "00:00");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xF5F2F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BANTpnl = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_BANTpnl, 56);
    lv_obj_set_height(ui_BANTpnl, 22);
    lv_obj_set_x(ui_BANTpnl, 129);
    lv_obj_set_y(ui_BANTpnl, -199);
    lv_obj_set_align(ui_BANTpnl, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BANTpnl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BANTpnl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BANTpnl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BANTpnl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BANTpnl, lv_color_hex(0xCFCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BANTpnl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel6, 190);
    lv_obj_set_height(ui_Panel6, 21);
    lv_obj_set_x(ui_Panel6, -71);
    lv_obj_set_y(ui_Panel6, 130);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0xEBC80A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_STEPpnl = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_STEPpnl, 203);
    lv_obj_set_height(ui_STEPpnl, 75);
    lv_obj_set_x(ui_STEPpnl, 62);
    lv_obj_set_y(ui_STEPpnl, -38);
    lv_obj_set_align(ui_STEPpnl, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_STEPpnl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_STEPpnl, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_STEPpnl, lv_color_hex(0x0F3460), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_STEPpnl, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_STEPpnl, lv_color_hex(0xB1A6A6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_STEPpnl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_STEPpnl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_stepLBL = lv_label_create(ui_STEPpnl);
    lv_obj_set_width(ui_stepLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_stepLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_stepLBL, -4);
    lv_obj_set_y(ui_stepLBL, 6);
    lv_obj_set_align(ui_stepLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_stepLBL, "0");
    lv_obj_set_style_text_font(ui_stepLBL, &ui_font_STEP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 128);
    lv_obj_set_height(ui_Panel1, 172);
    lv_obj_set_x(ui_Panel1, 99);
    lv_obj_set_y(ui_Panel1, 122);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x113C60), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x7BAAC5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_batLBL = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_batLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_batLBL, 129);
    lv_obj_set_y(ui_batLBL, -199);
    lv_obj_set_align(ui_batLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_batLBL, "");
    lv_obj_set_style_text_font(ui_batLBL, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button3, 190);
    lv_obj_set_height(ui_Button3, 60);
    lv_obj_set_x(ui_Button3, -71);
    lv_obj_set_y(ui_Button3, 177);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x79ABC0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, 4);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "START");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x061738), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_mid, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_disLBL = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_disLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_disLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_disLBL, 17);
    lv_obj_set_y(ui_disLBL, 287);
    lv_label_set_text(ui_disLBL, "0");
    lv_obj_set_style_text_font(ui_disLBL, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tresLBL2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_tresLBL2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tresLBL2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tresLBL2, -63);
    lv_obj_set_y(ui_tresLBL2, -7);
    lv_obj_set_align(ui_tresLBL2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tresLBL2, "1.75");
    lv_obj_set_style_text_color(ui_tresLBL2, lv_color_hex(0xA5C6E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tresLBL2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tresLBL2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button4, 91);
    lv_obj_set_height(ui_Button4, 54);
    lv_obj_set_x(ui_Button4, 118);
    lv_obj_set_y(ui_Button4, -150);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x7BAAC5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 0);
    lv_obj_set_y(ui_Label8, 3);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "SET");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &ui_font_mid, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -104);
    lv_obj_set_y(ui_Label2, 48);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "DISTANCE");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x97D3EA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -129);
    lv_obj_set_y(ui_Label3, 130);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "STEP ");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StepdisLBL = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_StepdisLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StepdisLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StepdisLBL, 164);
    lv_obj_set_y(ui_StepdisLBL, 344);
    lv_label_set_text(ui_StepdisLBL, "0.75");
    lv_obj_set_style_text_color(ui_StepdisLBL, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StepdisLBL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StepdisLBL, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -115);
    lv_obj_set_y(ui_Label10, -10);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "SENSITIVITY \nSENSOR\n");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xB8B5B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 69);
    lv_obj_set_y(ui_Label11, 57);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "SPEED");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x7BAAC5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &ui_font_micro, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_secLBL = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_secLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_secLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_secLBL, 25);
    lv_obj_set_y(ui_secLBL, -161);
    lv_obj_set_align(ui_secLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_secLBL, "00");
    lv_obj_set_style_text_color(ui_secLBL, lv_color_hex(0xADA4A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_secLBL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_secLBL, &ui_font_secFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -74);
    lv_obj_set_y(ui_Label13, -59);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "   STEPS    ");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xD3DAE7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &ui_font_mini, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label13, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label13, lv_color_hex(0x1A4387), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speedLBL = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_speedLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_speedLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_speedLBL, 98);
    lv_obj_set_y(ui_speedLBL, 93);
    lv_obj_set_align(ui_speedLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_speedLBL, "0.00");
    lv_obj_set_style_text_font(ui_speedLBL, &ui_font_SPD, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -93);
    lv_obj_set_y(ui_Label12, -199);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "VOLOS PROJECTS");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x8AC8E0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 163);
    lv_obj_set_height(ui_Panel2, 2);
    lv_obj_set_x(ui_Panel2, 82);
    lv_obj_set_y(ui_Panel2, -99);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xC1B7B7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -112);
    lv_obj_set_y(ui_Label14, 105);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "CALORIES:");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0x97D3EA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_caloriesLBL = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_caloriesLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_caloriesLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_caloriesLBL, -161);
    lv_obj_set_y(ui_caloriesLBL, -108);
    lv_obj_set_align(ui_caloriesLBL, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_caloriesLBL, "0.00");
    lv_obj_set_style_text_font(ui_caloriesLBL, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -10);
    lv_obj_set_y(ui_Label15, 80);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "METERS");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xCCC4CC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel4, 39);
    lv_obj_set_height(ui_Panel4, 16);
    lv_obj_set_x(ui_Panel4, 24);
    lv_obj_set_y(ui_Panel4, -133);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xEECA08), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 25);
    lv_obj_set_y(ui_Label16, -133);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "TIME");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label16, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel5, 187);
    lv_obj_set_height(ui_Panel5, 6);
    lv_obj_set_x(ui_Panel5, 70);
    lv_obj_set_y(ui_Panel5, 21);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0xEECA08), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -100);
    lv_obj_set_y(ui_Label17, 24);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "WALK STATISTIC");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0xEECA08), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -87);
    lv_obj_set_y(ui_Label18, -104);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "AWSOME STEP COUNTER");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0xA88DA8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image2, &ui_img_1537598557);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image2, -7);
    lv_obj_set_y(ui_Image2, -199);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 230);

    ui_Label19 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 83);
    lv_obj_set_y(ui_Label19, -107);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "WAVESHARE 1.8 AMOLED ESP32");
    lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0x95930F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BANTpnl1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_BANTpnl1, 7);
    lv_obj_set_height(ui_BANTpnl1, 12);
    lv_obj_set_x(ui_BANTpnl1, 158);
    lv_obj_set_y(ui_BANTpnl1, -200);
    lv_obj_set_align(ui_BANTpnl1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BANTpnl1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BANTpnl1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BANTpnl1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BANTpnl1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BANTpnl1, lv_color_hex(0xCFCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BANTpnl1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner2 = lv_spinner_create(ui_Screen1, 1000, 90);
    lv_obj_set_width(ui_Spinner2, 20);
    lv_obj_set_height(ui_Spinner2, 22);
    lv_obj_set_x(ui_Spinner2, 150);
    lv_obj_set_y(ui_Spinner2, -62);
    lv_obj_set_align(ui_Spinner2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Spinner2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Spinner2, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_Spinner2, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Spinner2, lv_color_hex(0xE5E5F1), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Spinner2, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_sleepBar = lv_bar_create(ui_Screen1);
    lv_bar_set_range(ui_sleepBar, 0, 8000);
    lv_bar_set_value(ui_sleepBar, 10000, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_sleepBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_sleepBar, 156);
    lv_obj_set_height(ui_sleepBar, 3);
    lv_obj_set_x(ui_sleepBar, -87);
    lv_obj_set_y(ui_sleepBar, -114);
    lv_obj_set_align(ui_sleepBar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_sleepBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_sleepBar, lv_color_hex(0x737070), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sleepBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_sndPNL = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_sndPNL, 24);
    lv_obj_set_height(ui_sndPNL, 24);
    lv_obj_set_x(ui_sndPNL, 54);
    lv_obj_set_y(ui_sndPNL, -199);
    lv_obj_set_align(ui_sndPNL, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_sndPNL, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_sndPNL, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sndPNL, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_sndPNL, &ui_img_2038933285, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_sndPNL, lv_color_hex(0xBABAD2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_sndPNL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_sndPNL, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel3, 74);
    lv_obj_set_height(ui_Panel3, 5);
    lv_obj_set_x(ui_Panel3, -74);
    lv_obj_set_y(ui_Panel3, -43);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x0F3460), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_crgPNL = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_crgPNL, 24);
    lv_obj_set_height(ui_crgPNL, 24);
    lv_obj_set_x(ui_crgPNL, 83);
    lv_obj_set_y(ui_crgPNL, -199);
    lv_obj_set_align(ui_crgPNL, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_crgPNL, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_crgPNL, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_crgPNL, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_crgPNL, &ui_img_597475696, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_crgPNL, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel7, 50);
    lv_obj_set_height(ui_Panel7, 35);
    lv_obj_set_x(ui_Panel7, -141);
    lv_obj_set_y(ui_Panel7, -58);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0xEBC80A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weightLBL2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_weightLBL2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weightLBL2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weightLBL2, -150);
    lv_obj_set_y(ui_weightLBL2, -56);
    lv_obj_set_align(ui_weightLBL2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weightLBL2, "62");
    lv_obj_set_style_text_color(ui_weightLBL2, lv_color_hex(0xE0DEDE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weightLBL2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weightLBL2, &ui_font_micro, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, -127);
    lv_obj_set_y(ui_Label29, -53);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "kg");
    lv_obj_set_style_text_color(ui_Label29, lv_color_hex(0xA8A6A6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel8, 60);
    lv_obj_set_height(ui_Panel8, 25);
    lv_obj_set_x(ui_Panel8, -5);
    lv_obj_set_y(ui_Panel8, 50);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0xEBC80A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);

}
